sonar.projectKey=mini-task-manager
sonar.projectName=Mini Task Manager
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,e2e/playwright-report/**,e2e/test-results/**